apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: local-cluster
spec:
  clusterName: local-cluster
  admissionControl:
    listenOnCreates: true
    listenOnEvents: true
    listenOnUpdates: true
    timeoutSeconds: 20
    contactImageScanners: DoNotScanInline
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
  scannerV4:
    db:
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
    indexer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 3
        minReplicas: 1
        replicas: 1
    scannerComponent: AutoSense
  monitoring:
    openshift:
      enabled: true
  auditLogs:
    collection: Auto
